//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AAULANHOMEPAGEModel", "FK_Event_Games", "Games", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AAULAN.Models.Games), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.Event), true)]
[assembly: EdmRelationshipAttribute("AAULANHOMEPAGEModel", "FK_Event_LAN", "LAN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AAULAN.Models.LAN), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.Event), true)]
[assembly: EdmRelationshipAttribute("AAULANHOMEPAGEModel", "SeatSeatingPlan", "Seat", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.Seat), "SeatingPlan", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AAULAN.Models.SeatingPlan), true)]
[assembly: EdmRelationshipAttribute("AAULANHOMEPAGEModel", "SeatingPlanLAN", "SeatingPlan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.SeatingPlan), "LAN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AAULAN.Models.LAN), true)]
[assembly: EdmRelationshipAttribute("AAULANHOMEPAGEModel", "UserSeat", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AAULAN.Models.User), "Seat", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.Seat))]
[assembly: EdmRelationshipAttribute("AAULANHOMEPAGEModel", "TeamMemberUser", "TeamMember", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AAULAN.Models.TeamMember), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AAULAN.Models.User))]
[assembly: EdmRelationshipAttribute("AAULANHOMEPAGEModel", "TeamMemberTeam", "TeamMember", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.TeamMember), "Team", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.Team))]
[assembly: EdmRelationshipAttribute("AAULANHOMEPAGEModel", "EventTeam", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.Event), "Team", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AAULAN.Models.Team))]

#endregion

namespace AAULAN.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AAULANHOMEPAGEEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AAULANHOMEPAGEEntities1 object using the connection string found in the 'AAULANHOMEPAGEEntities1' section of the application configuration file.
        /// </summary>
        public AAULANHOMEPAGEEntities1() : base("name=AAULANHOMEPAGEEntities1", "AAULANHOMEPAGEEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AAULANHOMEPAGEEntities1 object.
        /// </summary>
        public AAULANHOMEPAGEEntities1(string connectionString) : base(connectionString, "AAULANHOMEPAGEEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AAULANHOMEPAGEEntities1 object.
        /// </summary>
        public AAULANHOMEPAGEEntities1(EntityConnection connection) : base(connection, "AAULANHOMEPAGEEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Event> Event
        {
            get
            {
                if ((_Event == null))
                {
                    _Event = base.CreateObjectSet<Event>("Event");
                }
                return _Event;
            }
        }
        private ObjectSet<Event> _Event;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Games> Games
        {
            get
            {
                if ((_Games == null))
                {
                    _Games = base.CreateObjectSet<Games>("Games");
                }
                return _Games;
            }
        }
        private ObjectSet<Games> _Games;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LAN> LAN
        {
            get
            {
                if ((_LAN == null))
                {
                    _LAN = base.CreateObjectSet<LAN>("LAN");
                }
                return _LAN;
            }
        }
        private ObjectSet<LAN> _LAN;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Mad> Mad
        {
            get
            {
                if ((_Mad == null))
                {
                    _Mad = base.CreateObjectSet<Mad>("Mad");
                }
                return _Mad;
            }
        }
        private ObjectSet<Mad> _Mad;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Seat> Seat
        {
            get
            {
                if ((_Seat == null))
                {
                    _Seat = base.CreateObjectSet<Seat>("Seat");
                }
                return _Seat;
            }
        }
        private ObjectSet<Seat> _Seat;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeatingPlan> SeatingPlan
        {
            get
            {
                if ((_SeatingPlan == null))
                {
                    _SeatingPlan = base.CreateObjectSet<SeatingPlan>("SeatingPlan");
                }
                return _SeatingPlan;
            }
        }
        private ObjectSet<SeatingPlan> _SeatingPlan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pizza> PizzaSet
        {
            get
            {
                if ((_PizzaSet == null))
                {
                    _PizzaSet = base.CreateObjectSet<Pizza>("PizzaSet");
                }
                return _PizzaSet;
            }
        }
        private ObjectSet<Pizza> _PizzaSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Team> TeamSet
        {
            get
            {
                if ((_TeamSet == null))
                {
                    _TeamSet = base.CreateObjectSet<Team>("TeamSet");
                }
                return _TeamSet;
            }
        }
        private ObjectSet<Team> _TeamSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TeamMember> TeamMemberSet
        {
            get
            {
                if ((_TeamMemberSet == null))
                {
                    _TeamMemberSet = base.CreateObjectSet<TeamMember>("TeamMemberSet");
                }
                return _TeamMemberSet;
            }
        }
        private ObjectSet<TeamMember> _TeamMemberSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Event EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvent(Event @event)
        {
            base.AddObject("Event", @event);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Games EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGames(Games games)
        {
            base.AddObject("Games", games);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LAN EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLAN(LAN lAN)
        {
            base.AddObject("LAN", lAN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Mad EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMad(Mad mad)
        {
            base.AddObject("Mad", mad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Seat EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeat(Seat seat)
        {
            base.AddObject("Seat", seat);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeatingPlan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeatingPlan(SeatingPlan seatingPlan)
        {
            base.AddObject("SeatingPlan", seatingPlan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PizzaSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPizzaSet(Pizza pizza)
        {
            base.AddObject("PizzaSet", pizza);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TeamSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeamSet(Team team)
        {
            base.AddObject("TeamSet", team);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TeamMemberSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeamMemberSet(TeamMember teamMember)
        {
            base.AddObject("TeamMemberSet", teamMember);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="startTime">Initial value of the StartTime property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="endTime">Initial value of the EndTime property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="lANID">Initial value of the LANID property.</param>
        public static Event CreateEvent(global::System.DateTime startTime, global::System.String name, global::System.DateTime endTime, global::System.Int32 id, global::System.Int32 lANID)
        {
            Event @event = new Event();
            @event.StartTime = startTime;
            @event.Name = name;
            @event.EndTime = endTime;
            @event.ID = id;
            @event.LANID = lANID;
            return @event;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value, "StartTime");
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value, "EndTime");
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private global::System.DateTime _EndTime;
        partial void OnEndTimeChanging(global::System.DateTime value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LANID
        {
            get
            {
                return _LANID;
            }
            set
            {
                OnLANIDChanging(value);
                ReportPropertyChanging("LANID");
                _LANID = StructuralObject.SetValidValue(value, "LANID");
                ReportPropertyChanged("LANID");
                OnLANIDChanged();
            }
        }
        private global::System.Int32 _LANID;
        partial void OnLANIDChanging(global::System.Int32 value);
        partial void OnLANIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GAMEID
        {
            get
            {
                return _GAMEID;
            }
            set
            {
                OnGAMEIDChanging(value);
                ReportPropertyChanging("GAMEID");
                _GAMEID = StructuralObject.SetValidValue(value, "GAMEID");
                ReportPropertyChanged("GAMEID");
                OnGAMEIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GAMEID;
        partial void OnGAMEIDChanging(Nullable<global::System.Int32> value);
        partial void OnGAMEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rules
        {
            get
            {
                return _Rules;
            }
            set
            {
                OnRulesChanging(value);
                ReportPropertyChanging("Rules");
                _Rules = StructuralObject.SetValidValue(value, true, "Rules");
                ReportPropertyChanged("Rules");
                OnRulesChanged();
            }
        }
        private global::System.String _Rules;
        partial void OnRulesChanging(global::System.String value);
        partial void OnRulesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FoodID
        {
            get
            {
                return _FoodID;
            }
            set
            {
                OnFoodIDChanging(value);
                ReportPropertyChanging("FoodID");
                _FoodID = StructuralObject.SetValidValue(value, "FoodID");
                ReportPropertyChanged("FoodID");
                OnFoodIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FoodID;
        partial void OnFoodIDChanging(Nullable<global::System.Int32> value);
        partial void OnFoodIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "FK_Event_Games", "Games")]
        public Games Games
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Games>("AAULANHOMEPAGEModel.FK_Event_Games", "Games").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Games>("AAULANHOMEPAGEModel.FK_Event_Games", "Games").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Games> GamesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Games>("AAULANHOMEPAGEModel.FK_Event_Games", "Games");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Games>("AAULANHOMEPAGEModel.FK_Event_Games", "Games", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "FK_Event_LAN", "LAN")]
        public LAN LAN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LAN>("AAULANHOMEPAGEModel.FK_Event_LAN", "LAN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LAN>("AAULANHOMEPAGEModel.FK_Event_LAN", "LAN").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LAN> LANReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LAN>("AAULANHOMEPAGEModel.FK_Event_LAN", "LAN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LAN>("AAULANHOMEPAGEModel.FK_Event_LAN", "LAN", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "EventTeam", "Team")]
        public EntityCollection<Team> Team
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Team>("AAULANHOMEPAGEModel.EventTeam", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Team>("AAULANHOMEPAGEModel.EventTeam", "Team", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="Games")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Games : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Games object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Games CreateGames(global::System.Int32 id, global::System.String description, global::System.String name)
        {
            Games games = new Games();
            games.ID = id;
            games.Description = description;
            games.Name = name;
            return games;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DL_Link
        {
            get
            {
                return _DL_Link;
            }
            set
            {
                OnDL_LinkChanging(value);
                ReportPropertyChanging("DL_Link");
                _DL_Link = StructuralObject.SetValidValue(value, true, "DL_Link");
                ReportPropertyChanged("DL_Link");
                OnDL_LinkChanged();
            }
        }
        private global::System.String _DL_Link;
        partial void OnDL_LinkChanging(global::System.String value);
        partial void OnDL_LinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "FK_Event_Games", "Event")]
        public EntityCollection<Event> Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("AAULANHOMEPAGEModel.FK_Event_Games", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("AAULANHOMEPAGEModel.FK_Event_Games", "Event", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="LAN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LAN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LAN object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="startTime">Initial value of the StartTime property.</param>
        /// <param name="endTime">Initial value of the EndTime property.</param>
        public static LAN CreateLAN(global::System.Int32 id, global::System.DateTime startTime, global::System.DateTime endTime)
        {
            LAN lAN = new LAN();
            lAN.ID = id;
            lAN.StartTime = startTime;
            lAN.EndTime = endTime;
            return lAN;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value, "StartTime");
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.DateTime _StartTime;
        partial void OnStartTimeChanging(global::System.DateTime value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value, "EndTime");
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private global::System.DateTime _EndTime;
        partial void OnEndTimeChanging(global::System.DateTime value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true, "Location");
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "FK_Event_LAN", "Event")]
        public EntityCollection<Event> Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("AAULANHOMEPAGEModel.FK_Event_LAN", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("AAULANHOMEPAGEModel.FK_Event_LAN", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "SeatingPlanLAN", "SeatingPlan")]
        public EntityCollection<SeatingPlan> SeatingPlan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeatingPlan>("AAULANHOMEPAGEModel.SeatingPlanLAN", "SeatingPlan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeatingPlan>("AAULANHOMEPAGEModel.SeatingPlanLAN", "SeatingPlan", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="Mad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Mad object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="paid">Initial value of the Paid property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="eVENTID">Initial value of the EVENTID property.</param>
        public static Mad CreateMad(global::System.String name, global::System.Boolean paid, global::System.Int32 number, global::System.Int32 id, global::System.Int32 eVENTID)
        {
            Mad mad = new Mad();
            mad.Name = name;
            mad.Paid = paid;
            mad.Number = number;
            mad.ID = id;
            mad.EVENTID = eVENTID;
            return mad;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Paid
        {
            get
            {
                return _Paid;
            }
            set
            {
                OnPaidChanging(value);
                ReportPropertyChanging("Paid");
                _Paid = StructuralObject.SetValidValue(value, "Paid");
                ReportPropertyChanged("Paid");
                OnPaidChanged();
            }
        }
        private global::System.Boolean _Paid;
        partial void OnPaidChanging(global::System.Boolean value);
        partial void OnPaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true, "Note");
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, "Number");
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EVENTID
        {
            get
            {
                return _EVENTID;
            }
            set
            {
                OnEVENTIDChanging(value);
                ReportPropertyChanging("EVENTID");
                _EVENTID = StructuralObject.SetValidValue(value, "EVENTID");
                ReportPropertyChanged("EVENTID");
                OnEVENTIDChanged();
            }
        }
        private global::System.Int32 _EVENTID;
        partial void OnEVENTIDChanging(global::System.Int32 value);
        partial void OnEVENTIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="Pizza")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pizza : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pizza object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static Pizza CreatePizza(global::System.Int32 id, global::System.Int32 number, global::System.Decimal price)
        {
            Pizza pizza = new Pizza();
            pizza.Id = id;
            pizza.Number = number;
            pizza.Price = price;
            return pizza;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, "Number");
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="Seat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Seat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Seat object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="taken">Initial value of the Taken property.</param>
        /// <param name="seatingPlanId">Initial value of the SeatingPlanId property.</param>
        public static Seat CreateSeat(global::System.Int32 id, global::System.Boolean taken, global::System.Int32 seatingPlanId)
        {
            Seat seat = new Seat();
            seat.Id = id;
            seat.Taken = taken;
            seat.SeatingPlanId = seatingPlanId;
            return seat;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Taken
        {
            get
            {
                return _Taken;
            }
            set
            {
                OnTakenChanging(value);
                ReportPropertyChanging("Taken");
                _Taken = StructuralObject.SetValidValue(value, "Taken");
                ReportPropertyChanged("Taken");
                OnTakenChanged();
            }
        }
        private global::System.Boolean _Taken;
        partial void OnTakenChanging(global::System.Boolean value);
        partial void OnTakenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SeatingPlanId
        {
            get
            {
                return _SeatingPlanId;
            }
            set
            {
                OnSeatingPlanIdChanging(value);
                ReportPropertyChanging("SeatingPlanId");
                _SeatingPlanId = StructuralObject.SetValidValue(value, "SeatingPlanId");
                ReportPropertyChanged("SeatingPlanId");
                OnSeatingPlanIdChanged();
            }
        }
        private global::System.Int32 _SeatingPlanId;
        partial void OnSeatingPlanIdChanging(global::System.Int32 value);
        partial void OnSeatingPlanIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "SeatSeatingPlan", "SeatingPlan")]
        public SeatingPlan SeatingPlan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeatingPlan>("AAULANHOMEPAGEModel.SeatSeatingPlan", "SeatingPlan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeatingPlan>("AAULANHOMEPAGEModel.SeatSeatingPlan", "SeatingPlan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SeatingPlan> SeatingPlanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SeatingPlan>("AAULANHOMEPAGEModel.SeatSeatingPlan", "SeatingPlan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SeatingPlan>("AAULANHOMEPAGEModel.SeatSeatingPlan", "SeatingPlan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "UserSeat", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AAULANHOMEPAGEModel.UserSeat", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AAULANHOMEPAGEModel.UserSeat", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AAULANHOMEPAGEModel.UserSeat", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("AAULANHOMEPAGEModel.UserSeat", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="SeatingPlan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeatingPlan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeatingPlan object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="lANID">Initial value of the LANID property.</param>
        public static SeatingPlan CreateSeatingPlan(global::System.Int32 id, global::System.Int32 lANID)
        {
            SeatingPlan seatingPlan = new SeatingPlan();
            seatingPlan.Id = id;
            seatingPlan.LANID = lANID;
            return seatingPlan;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LANID
        {
            get
            {
                return _LANID;
            }
            set
            {
                OnLANIDChanging(value);
                ReportPropertyChanging("LANID");
                _LANID = StructuralObject.SetValidValue(value, "LANID");
                ReportPropertyChanged("LANID");
                OnLANIDChanged();
            }
        }
        private global::System.Int32 _LANID;
        partial void OnLANIDChanging(global::System.Int32 value);
        partial void OnLANIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "SeatSeatingPlan", "Seat")]
        public EntityCollection<Seat> Seat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Seat>("AAULANHOMEPAGEModel.SeatSeatingPlan", "Seat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Seat>("AAULANHOMEPAGEModel.SeatSeatingPlan", "Seat", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "SeatingPlanLAN", "LAN")]
        public LAN LAN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LAN>("AAULANHOMEPAGEModel.SeatingPlanLAN", "LAN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LAN>("AAULANHOMEPAGEModel.SeatingPlanLAN", "LAN").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LAN> LANReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LAN>("AAULANHOMEPAGEModel.SeatingPlanLAN", "LAN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LAN>("AAULANHOMEPAGEModel.SeatingPlanLAN", "LAN", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="Team")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Team : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Team object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="standaloneTeam">Initial value of the StandaloneTeam property.</param>
        public static Team CreateTeam(global::System.Int32 id, global::System.String name, global::System.String password, global::System.Boolean standaloneTeam)
        {
            Team team = new Team();
            team.Id = id;
            team.Name = name;
            team.Password = password;
            team.StandaloneTeam = standaloneTeam;
            return team;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean StandaloneTeam
        {
            get
            {
                return _StandaloneTeam;
            }
            set
            {
                OnStandaloneTeamChanging(value);
                ReportPropertyChanging("StandaloneTeam");
                _StandaloneTeam = StructuralObject.SetValidValue(value, "StandaloneTeam");
                ReportPropertyChanged("StandaloneTeam");
                OnStandaloneTeamChanged();
            }
        }
        private global::System.Boolean _StandaloneTeam;
        partial void OnStandaloneTeamChanging(global::System.Boolean value);
        partial void OnStandaloneTeamChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "TeamMemberTeam", "TeamMember")]
        public EntityCollection<TeamMember> TeamMember
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TeamMember>("AAULANHOMEPAGEModel.TeamMemberTeam", "TeamMember");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TeamMember>("AAULANHOMEPAGEModel.TeamMemberTeam", "TeamMember", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "EventTeam", "Event")]
        public EntityCollection<Event> Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("AAULANHOMEPAGEModel.EventTeam", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("AAULANHOMEPAGEModel.EventTeam", "Event", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="TeamMember")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TeamMember : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TeamMember object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="teamId">Initial value of the TeamId property.</param>
        public static TeamMember CreateTeamMember(global::System.Int32 id, global::System.Int32 teamId)
        {
            TeamMember teamMember = new TeamMember();
            teamMember.Id = id;
            teamMember.TeamId = teamId;
            return teamMember;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeamId
        {
            get
            {
                return _TeamId;
            }
            set
            {
                OnTeamIdChanging(value);
                ReportPropertyChanging("TeamId");
                _TeamId = StructuralObject.SetValidValue(value, "TeamId");
                ReportPropertyChanged("TeamId");
                OnTeamIdChanged();
            }
        }
        private global::System.Int32 _TeamId;
        partial void OnTeamIdChanging(global::System.Int32 value);
        partial void OnTeamIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "TeamMemberUser", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AAULANHOMEPAGEModel.TeamMemberUser", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AAULANHOMEPAGEModel.TeamMemberUser", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("AAULANHOMEPAGEModel.TeamMemberUser", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("AAULANHOMEPAGEModel.TeamMemberUser", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "TeamMemberTeam", "Team")]
        public EntityCollection<Team> Team
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Team>("AAULANHOMEPAGEModel.TeamMemberTeam", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Team>("AAULANHOMEPAGEModel.TeamMemberTeam", "Team", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AAULANHOMEPAGEModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="role">Initial value of the Role property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static User CreateUser(global::System.String username, global::System.String password, global::System.String role, global::System.String email)
        {
            User user = new User();
            user.Username = username;
            user.Password = password;
            user.Role = role;
            user.Email = email;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                if (_Username != value)
                {
                    OnUsernameChanging(value);
                    ReportPropertyChanging("Username");
                    _Username = StructuralObject.SetValidValue(value, false, "Username");
                    ReportPropertyChanged("Username");
                    OnUsernameChanged();
                }
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, false, "Role");
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "UserSeat", "Seat")]
        public EntityCollection<Seat> Seat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Seat>("AAULANHOMEPAGEModel.UserSeat", "Seat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Seat>("AAULANHOMEPAGEModel.UserSeat", "Seat", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AAULANHOMEPAGEModel", "TeamMemberUser", "TeamMember")]
        public TeamMember TeamMember
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TeamMember>("AAULANHOMEPAGEModel.TeamMemberUser", "TeamMember").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TeamMember>("AAULANHOMEPAGEModel.TeamMemberUser", "TeamMember").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TeamMember> TeamMemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TeamMember>("AAULANHOMEPAGEModel.TeamMemberUser", "TeamMember");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TeamMember>("AAULANHOMEPAGEModel.TeamMemberUser", "TeamMember", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
